name: vs_live
description: "Billion sport live application."
publish_to: "none"
version: 1.3.0+25

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  equatable: ^2.0.8
  flutter_hooks:
  hooks_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0
  url_launcher: ^6.3.2
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  go_router: ^17.0.1
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.4
  envied: ^1.3.2

  # video player
  video_player: ^2.10.1
  chewie: ^1.13.0

  webview_flutter: ^4.13.1
  webview_flutter_wkwebview: ^3.23.5
  youtube_player_iframe: ^5.2.2

  cached_network_image: ^3.4.1
  gpt_markdown: ^1.1.5
  native_id: ^1.0.0

  firebase_core: ^4.3.0
  firebase_remote_config: ^6.1.3
  firebase_analytics: ^12.1.0
  firebase_crashlytics: ^5.0.6

  flutter_staggered_grid_view: ^0.7.0
  package_info_plus: ^9.0.0
  wakelock_plus: ^1.4.0
  pub_semver: ^2.2.0
  wiredash: ^2.6.0

  device_preview: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner:
  riverpod_generator: ^4.0.0+1
  json_serializable: ^6.11.2
  envied_generator: ^1.3.2

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/player.html
    - assets/images/
    - assets/github.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
